name: Manage Azure VM Replication

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Resource Group Name'
        required: true
        type: string
      vaultName:
        description: 'Recovery Services Vault Name'
        required: true
        type: string
      vmName:
        description: 'VM Name'
        required: true
        type: string
      #subscriptionId:
      #  description: 'Azure Subscription ID'
      #  required: true
      #  type: string
      #policyName:
      #  description: 'Azure ASR Policy Name'
      #  required: true
      #  type: string
      targetResourceGroupName:
        description: 'Target Resource Group Name'
        required: true
        type: string
      sourceLocation:
        description: 'Source Location'
        required: true
        type: string
      targetLocation:
        description: 'Target Location'
        required: true
        type: string
      targetNetworkId:
        description: 'Target Network ID'
        required: true
        type: string
      targetSubnetName:
        description: 'Target Subnet Name'
        required: true
        type: string
      cacheStorageAccountId:
        description: 'Cache Storage Account ID'
        required: true
        type: string
      #replicationStorageType:
      #  description: 'Replication Storage Type'
      #  required: true
      #  type: string
      #replicateAvailabilitySet:
      #  description: 'Replicate Availability Set'
      #  required: false
      #  type: string
      staticIP:
        description: 'Static IP Address'
        required: true
        type: string

jobs:
  disable-replication:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Run Disable Replication Script
      run: |
        # Ensure you have the script in your repository or provide its path
        .\scripts\disable-vmreplication.ps1 `
          -ResourceGroupName ${{ inputs.resourceGroupName }} `
          -VaultName ${{ inputs.vaultName }} `
          -VMName ${{ inputs.vmName }} `
          #-SubscriptionId ${{ inputs.subscriptionId }}
      shell: pwsh
      env:
        INPUT_CLIENTSECRET: ${{ secrets.AZURE_CLIENT_SECRET}} 
        INPUT_CLIENTID: ${{ secrets.AZURE_CLIENT_ID }}

  enable-replication:
    runs-on: [self-hosted]
    needs: disable-replication

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    #- name: Set up Azure PowerShell
    #  uses: Azure/setup-powershell@v1
    #  with:
    #    azps-version: '10.13.0'  # Adjust based on your version preference

    - name: Run Enable Replication Script
      run: |
        # Ensure you have the script in your repository or provide its path
        .\scripts\enable-vmreplication.ps1 `
          -ResourceGroupName ${{ inputs.resourceGroupName }} `
          -VaultName ${{ inputs.vaultName }} `
          -VMName ${{ inputs.vmName }} `
          -SubscriptionId ${{ inputs.subscriptionId }} `
          -PolicyName ${{ inputs.policyName }} `
          -TargetResourceGroupName ${{ inputs.targetResourceGroupName }} `
          -SourceLocation ${{ inputs.sourceLocation }} `
          -TargetLocation ${{ inputs.targetLocation }} `
          -TargetNetworkId ${{ inputs.targetNetworkId }} `
          -TargetSubnetName ${{ inputs.targetSubnetName }} `
          -CacheStorageAccountId ${{ inputs.cacheStorageAccountId }} `
          -ReplicationStorageType ${{ inputs.replicationStorageType }} `
          -ReplicateAvailabilitySet ${{ inputs.replicateAvailabilitySet }} `
          -StaticIP ${{ inputs.staticIP }}
      shell: pwsh
      env:
        INPUT_CLIENTSECRET: ${{ secrets.AZURE_CLIENT_SECRET}} 
        INPUT_CLIENTID: ${{ secrets.AZURE_CLIENT_ID }}